FROM openjdk:21-jdk-slim
WORKDIR /app

RUN apt-get update && apt-get install -y maven && apt-get clean

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "target/*.jar"]