FROM openjdk:21-jdk-slim
WORKDIR /app

# Install Maven 4.0
RUN apt-get update && apt-get install -y maven && apt-get clean

# Copy Maven project files
COPY pom.xml .
COPY src ./src

# Build the application
RUN mvn clean package -DskipTests

# Run the application
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "target/*.jar"]